name: SecurityChecks
on:
  pull_request: {}
  push:
    branches: ["update_semgrep"]
  schedule:
    - cron: '30 20 * * *'

  workflow_call:
    inputs:
      SEMGREP_MANDATORY:
        description: 'Run semgrep as mandatory or not'
        default: 'true'
        required: false
        type: string
      RUNNER_NAME:
        description: 'Github runner name'
        default: 'self-hosted'
        required: true
        type: string
    secrets:
      SEMGREP_APP_TOKEN:
        description: 'needed for semgrep'
        required: true

jobs:
  semgrep:
    name: Semgrep
    runs-on: [ 'k8s-runner',  '${{ inputs.RUNNER_NAME }}' ]
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Run semgrep
        run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
